spring:
  application:
    name: sample-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: >
            classpath:config/services/foo,

server:
  port: 8899
